# Define Firmware Version Number
export PRJ_VERSION = 0x00000001

# Define target output
target: vcs

# Define target part
export PRJ_PART = XC7K160TFFG676-2

# Use top level makefile
include ../../submodules/ruckus/system_vivado.mk
