# Define Firmware Version Number
export PRJ_VERSION = 0x00000001

# Define target output
target: vcs

# Define target part
export PRJ_PART = XCKU040-FFVA1156-2-E

# MISC. variables
export AMC_ADV_BUILD = 1
export RTM_ETH = 0
export AMC_TYPE_BAY0 = AmcMpsSfp
export AMC_INTF_BAY0 = Version2
export AMC_TYPE_BAY1 = AmcMpsSfp
export AMC_INTF_BAY1 = Version2
export RTM_TYPE = RtmEmpty
export RTM_INTF = Version2
export COMMON_FILE = AppCommon

# Use top level makefile
include ../../submodules/ruckus/system_vivado.mk
