##############################################################################
## This file is part of 'LCLS2 LLRF Firmware'.
## It is subject to the license terms in the LICENSE.txt file found in the 
## top-level directory of this distribution and at: 
##    https://confluence.slac.stanford.edu/display/ppareg/LICENSE.html. 
## No part of 'LCLS2 LLRF Firmware', including this file, 
## may be copied, modified, propagated, or distributed except according to 
## the terms contained in the LICENSE.txt file.
##############################################################################
#schemaversion 3.0.0
#once Application.yaml
#include BsaMpsMsgRxCore.yaml
#include BsaMpsMsgRxCombine.yaml

AppCore: &Application 
  name: Application
  description: AMC Carrier Application Core
  size: 0x80000000
  class: MMIODev
  configPrio: 1
  ########
  children:
  ########
    ##################################################     
    BsaMpsMsgRxCore:
      <<: *BsaMpsMsgRxCore
      at:
        offset: 0x00000000      
        stride: 0x10000000
        nelms: 2
    ##################################################     
    BsaMpsMsgRxCombine:
      <<: *BsaMpsMsgRxCombine
      at:
        offset: 0x20000000           
    ##################################################     
    