export GIT_BYPASS = 1

# Define Firmware Version Number
export PRJ_VERSION = 0x00000001

# Define target output
target: gui

# Define target part
export PRJ_PART = XCKU040-FFVA1156-2-E

# MISC. variables
export AMC_ADV_BUILD = 1
export RTM_ETH = 0
export AMC_TYPE_BAY0 = AmcMpsSfp
export AMC_INTF_BAY0 = 
export AMC_TYPE_BAY1 = AmcMpsSfp
export AMC_INTF_BAY1 = 
export RTM_TYPE = RtmEmpty
export RTM_INTF = Version1
export COMMON_FILE = AppCommon

# Keep unused source code 
export REMOVE_UNUSED_CODE = 0

# Use top level makefile
include ../../submodules/ruckus/system_vivado.mk
